// Generated by BUCKLESCRIPT VERSION 3.1.0, PLEASE EDIT WITH CARE
'use strict';

var Tape = require("bs-tape/src/Tape.bs.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Json$LidcoreBsJson = require("../src/json.js");

Tape.test("Parsing", (function (t) {
        var obj = /* `Object */[
          -908856609,
          /* :: */[
            /* tuple */[
              "foo",
              /* `Number */[
                -703661335,
                123.4
              ]
            ],
            /* [] */0
          ]
        ];
        Curry._1(t[/* plan */0], 5);
        Curry._2(t[/* ok */7], /* None */0, Caml_obj.caml_equal(obj, Json$LidcoreBsJson.parse("{\"foo\":123.4}")));
        Curry._2(t[/* ok */7], /* None */0, Caml_obj.caml_equal(obj, Json$LidcoreBsJson.parse(Json$LidcoreBsJson.stringify(obj))));
        Curry._2(t[/* ok */7], /* None */0, Caml_obj.caml_equal(/* `String */[
                  -976970511,
                  "aabbcc"
                ], Json$LidcoreBsJson.parse("\"aabbcc\"")));
        Curry._2(t[/* ok */7], /* None */0, "\"aabbcc\"" === Json$LidcoreBsJson.stringify(/* `String */[
                  -976970511,
                  "aabbcc"
                ]));
        return Curry._2(t[/* ok */7], /* None */0, Caml_obj.caml_equal(/* `Array */[
                        951901561,
                        /* array */[
                          /* `Number */[
                            -703661335,
                            1
                          ],
                          /* `String */[
                            -976970511,
                            "foo"
                          ],
                          /* Null */870828711
                        ]
                      ], Json$LidcoreBsJson.parse("[1,\"foo\",null]")));
      }));

/*  Not a pure module */
